### ISSUE TITLE
Ubuntu Installation Steps ?

### ISSUE THREAD

**Issue by imskanand** [jaxleof/dew#1]
Can you Please write down the All steps regarding installation in Ubuntu Linux?

**Comment by Kanna-Neko** [comment]
pay attention to you cpu arch, download and decompress is ok.
1. confirm your cpu arch
2. Download the compressed package in [release page](https://github.com/jaxleof/cf-helper/releases/tag/v1.0.0)
3. decompress it.
4. you will see cf-helper binary program in the folder.
5. use it in terminal

maybe I'm wrong, but this is the general process, you also can compile the program Individually. hope those can help you

**Comment by imskanand** [comment]
This is a basic step everyone Know.... But Thanks

**Comment by Kanna-Neko** [comment]
you mean a script shell like wget, tar -zxvf?
i will try later, I'm relatively unfamiliar with these steps.

**Comment by HydraBor** [comment]
An easy way. with golang installed, just `go install https://github.com/jaxleof/dew@master` is OK.
If author add a git tag to repo later, you can also use the tag.
