### ISSUE TITLE
can dew support rust ?

### ISSUE THREAD

**Issue by Abhinavpatel00** [jaxleof/dew#12]
hey i want to know is there a way to use dew with rust

**Comment by Kanna-Neko** [comment]
you should configurate language follow this guildline https://github.com/Kanna-Neko/dew?tab=readme-ov-file#how-to-config-the-language, and the rust programType is 75, if you have more question, you can ask more.

your configuration depending on the method of you use rust, nither rustc or cargo

**Comment by Abhinavpatel00** [comment]
ohk thank you so much how do i know progratype for haskell? and other languages?

**Comment by Abhinavpatel00** [comment]
thank you so much
