### ISSUE TITLE
[Suggestion] Enhance on file embed

### ISSUE THREAD

**Issue by HydraBor** [jaxleof/dew#2]
For file `https://github.com/jaxleof/dew/blob/master/cmd/init.go`, you can use `https://pkg.go.dev/embed` to embed template file, which is normally better for long-term maintainence.

For example
```golang
import _ "embed"

//go:embed ../template/cpp.cpp
var defaultCpp string

```

for 

https://github.com/jaxleof/dew/blob/e5ba7b69fcd459597975356fb664f1ba673e08df/cmd/init.go#L17-L54

**Comment by Kanna-Neko** [comment]
I think less is more, deal with package will waste more time.
