### ISSUE TITLE
password

### ISSUE THREAD

**Issue by worldcreaterwc** [jaxleof/dew#5]
密码是明文保存的，这是否有安全隐患？

**Comment by Kanna-Neko** [comment]
第一，我认为你是对的，但目前版本可能还存在bug，这样对于开发者来说容易检查bug在哪。
第二，我认为电脑中的私密文件很多，你需要一个密码来保护你的电脑，我认为这样就足以保护你的账号，毕竟所有的东西都是在本地运行。
第三，虽然codeforces账号对于我们来说很重要，但我认为codeforces账号没有足够的价值被人窃取，因为不法分子没有任何利益可言。
第四，如果在版本稳定后，并且有群体需要的情况下，我会考虑进行加密。

**Comment by Zxilly** [comment]
chrome 也是明文保存的，不是啥大事。
