### ISSUE TITLE
BUG: `dew init` error

### ISSUE THREAD

**Issue by lifeich1** [jaxleof/dew#6]
```
2023/04/21 00:57:16 update.go:146: invalid character '<' looking for beginning of value
```

![tmp-for-dew](https://user-images.githubusercontent.com/22391687/233437246-d1e9a61d-fca4-4adc-a515-37dc939fe7a6.png)

**Comment by Kanna-Neko** [comment]
1. I guess your network maybe is unstable, you can change your network environment and try again.
2. you can jump over this step and modify meta info in ./codeforces/config.yaml
