### ISSUE TITLE
提交代码失败

### ISSUE THREAD

**Issue by yangjl2022** [jaxleof/dew#9]
命令执行失败
它打开了我的提交记录，但是没有提交代码

![image](https://github.com/Kanna-Neko/dew/assets/105093095/d5c009fc-2cd5-49e6-919c-35b40ceda412)

![image](https://github.com/Kanna-Neko/dew/assets/105093095/8e6a4edd-659d-4332-9cae-8ef5b1d6c10e)

附使用的dew版本
![image](https://github.com/Kanna-Neko/dew/assets/105093095/9ab3a6e0-1016-4ab0-a413-3a5879ff38fe)

**Comment by Kanna-Neko** [comment]
别急，我看看

**Comment by Kanna-Neko** [comment]
我找到原因了，c++这个语言的配置项（GNU G++17 9.2.0 (64 bit, msys 2)）用不了，codeforces对编译器进行了升级，你可以使用c++17(使用 dew lang c++17命令)来解决这个问题。

后续版本会对默认配置文件进行修改。

**Comment by yangjl2022** [comment]
修改后命令是执行完了，没有冒红，但是仍然没有提交
![image](https://github.com/Kanna-Neko/dew/assets/105093095/e5ad4fcb-03f4-45e0-8fa9-bd4a3c816183)
只打开提交记录界面
![image](https://github.com/Kanna-Neko/dew/assets/105093095/3b03ffb3-8172-4b8a-b918-41cbb16e28a3)

**Comment by Kanna-Neko** [comment]
<img width="904" alt="image" src="https://github.com/Kanna-Neko/dew/assets/54601297/d38216ec-1d1f-4520-afa9-c9da2f5effe0">
我这边可以，你要不换道题目试试

**Comment by Kanna-Neko** [comment]
以下是我测试的时候使用的配置
<img width="522" alt="image" src="https://github.com/Kanna-Neko/dew/assets/54601297/a3ac8bd0-f24a-43bb-aa96-182877d35d27">

**Comment by yangjl2022** [comment]
我尝试了其他几个题目，仍然是没有帮我提交，只是打开了my submission界面；
我也重新git clone 了本项目，用 go build 编译后尝试过，
看你路径，是用的linux吗，我的是windows，是这个原因导致我们得到的效果不同？
![image](https://github.com/Kanna-Neko/dew/assets/105093095/bb76daaa-833f-401c-af46-21a7894a373a)

**Comment by Kanna-Neko** [comment]
我又尝试了一下，我还是可以，目前我也不太清楚原因，但应该不是操作系统的原因，这个工具目前只是使用了网络请求，和操作系统没什么关系，如果你有时间可以发个邮件给我，我加你qq一起研究一下。

email: moonandxinxin@gmail.com

**Comment by yangjl2022** [comment]
已发
